---
driver:
  name: vagrant

driver_config:
  require_chef_omnibus: true

platforms:
- name: centos-6.9
- name: centos-7.3

provisioner:
    name: chef_zero

suites:
- name: default
  run_list:
    - "recipe[chef_rvm::default]"
  attributes:
